
import './globals.css'
import { Inter } from 'next/font/google'
import ProjectModal from '@/src/Projects/ProjectModal'
import GoalsModal from '@/src/Goals/GoalsModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        {children}
    
        <ProjectModal />
    
        </body>
    </html>
  )
}
